server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/claimverse_auth
    username: postgres  # or 'postgres' if you're using that
    password: Satvika@0310  # use your actual password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: auth-service

jwt:
  secret: my-very-secret-jwt-key-1234567890123456
